// This file is auto-generated by @hey-api/openapi-ts

export const AdminCommentListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AdminCommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AdminCommentListPublic'
} as const;

export const AdminCommentPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        post_id: {
            type: 'integer',
            title: 'Post Id'
        },
        post_slug: {
            type: 'string',
            title: 'Post Slug'
        },
        post_title: {
            type: 'string',
            title: 'Post Title'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        author_name: {
            type: 'string',
            title: 'Author Name'
        },
        author_email: {
            type: 'string',
            title: 'Author Email'
        },
        author_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Url'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        status: {
            '$ref': '#/components/schemas/CommentStatus'
        }
    },
    type: 'object',
    required: ['id', 'post_id', 'post_slug', 'post_title', 'parent_id', 'author_name', 'author_email', 'author_url', 'body', 'created_at', 'status'],
    title: 'AdminCommentPublic'
} as const;

export const AdminCommentStatusUpdateSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/CommentStatus'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'AdminCommentStatusUpdate'
} as const;

export const AdminStreamCommentListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AdminStreamCommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AdminStreamCommentListPublic'
} as const;

export const AdminStreamCommentPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        content_id: {
            type: 'integer',
            title: 'Content Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        author_name: {
            type: 'string',
            title: 'Author Name'
        },
        author_email: {
            type: 'string',
            title: 'Author Email'
        },
        author_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Url'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        status: {
            '$ref': '#/components/schemas/CommentStatus'
        }
    },
    type: 'object',
    required: ['id', 'content_id', 'parent_id', 'author_name', 'author_email', 'author_url', 'body', 'created_at', 'status'],
    title: 'AdminStreamCommentPublic'
} as const;

export const AnimeDetailSchema = {
    properties: {
        content_id: {
            type: 'integer',
            title: 'Content Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        anime_name: {
            type: 'string',
            title: 'Anime Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        poster: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        backdrop: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        overview: {
            type: 'string',
            title: 'Overview'
        },
        duration: {
            type: 'integer',
            title: 'Duration'
        },
        rating: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Rating'
        },
        age_rating: {
            type: 'string',
            title: 'Age Rating'
        },
        genres: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Genres'
        },
        release_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Release Date'
        },
        seasons: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/SeasonSummary'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seasons'
        },
        links: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/LinkPublic'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Links'
        },
        watch_servers: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/DownloadLink'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Watch Servers'
        }
    },
    type: 'object',
    required: ['content_id', 'slug', 'anime_name', 'type', 'poster', 'backdrop', 'overview', 'duration', 'rating', 'age_rating', 'genres', 'release_date'],
    title: 'AnimeDetail'
} as const;

export const AnimeListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AnimeSummary'
            },
            type: 'array',
            title: 'Data'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'page', 'limit', 'count'],
    title: 'AnimeListPublic'
} as const;

export const AnimeSummarySchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        anime_name: {
            type: 'string',
            title: 'Anime Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        poster: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        rating: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Rating'
        },
        age_rating: {
            type: 'string',
            title: 'Age Rating'
        },
        genres: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Genres'
        },
        season_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Season Count'
        }
    },
    type: 'object',
    required: ['slug', 'anime_name', 'type', 'poster', 'rating', 'age_rating', 'genres', 'season_count'],
    title: 'AnimeSummary'
} as const;

export const AuthorAccessScopeSchema = {
    type: 'string',
    enum: ['all', 'ongoing', 'access_list'],
    title: 'AuthorAccessScope'
} as const;

export const AuthorPublicSchema = {
    properties: {
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        avatar_url: {
            type: 'string',
            title: 'Avatar Url'
        }
    },
    type: 'object',
    required: ['display_name', 'slug', 'avatar_url'],
    title: 'AuthorPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CommentCreateSchema = {
    properties: {
        author_name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Author Name'
        },
        author_email: {
            type: 'string',
            format: 'email',
            title: 'Author Email'
        },
        author_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Url'
        },
        body: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Body'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: ['author_name', 'author_email', 'body'],
    title: 'CommentCreate'
} as const;

export const CommentListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        root_count: {
            type: 'integer',
            title: 'Root Count'
        },
        total_count: {
            type: 'integer',
            title: 'Total Count'
        }
    },
    type: 'object',
    required: ['data', 'page', 'limit', 'root_count', 'total_count'],
    title: 'CommentListPublic'
} as const;

export const CommentPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        author_name: {
            type: 'string',
            title: 'Author Name'
        },
        author_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Url'
        },
        avatar_url: {
            type: 'string',
            title: 'Avatar Url'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'parent_id', 'author_name', 'author_url', 'avatar_url', 'body', 'created_at'],
    title: 'CommentPublic'
} as const;

export const CommentStatusSchema = {
    type: 'string',
    enum: ['pending', 'approved', 'spam'],
    title: 'CommentStatus'
} as const;

export const DownloadLinkSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        link_server_id: {
            type: 'integer',
            title: 'Link Server Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        }
    },
    type: 'object',
    required: ['name', 'link_server_id', 'color'],
    title: 'DownloadLink'
} as const;

export const EpisodeDetailSchema = {
    properties: {
        content_id: {
            type: 'integer',
            title: 'Content Id'
        },
        episode_number: {
            type: 'integer',
            title: 'Episode Number'
        },
        episode_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Name'
        },
        overview: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overview'
        },
        img: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        air_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Air Date'
        },
        episode_runtime: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Runtime'
        },
        episode_rating: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Rating'
        },
        links: {
            items: {
                '$ref': '#/components/schemas/LinkPublic'
            },
            type: 'array',
            title: 'Links'
        },
        watch_servers: {
            items: {
                '$ref': '#/components/schemas/DownloadLink'
            },
            type: 'array',
            title: 'Watch Servers'
        }
    },
    type: 'object',
    required: ['content_id', 'episode_number', 'episode_name', 'overview', 'img', 'air_date', 'episode_runtime', 'episode_rating', 'links', 'watch_servers'],
    title: 'EpisodeDetail'
} as const;

export const EpisodeSummarySchema = {
    properties: {
        episode_number: {
            type: 'integer',
            title: 'Episode Number'
        },
        episode_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Name'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        img: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        air_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Air Date'
        },
        episode_rating: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Rating'
        },
        link_count: {
            type: 'integer',
            title: 'Link Count'
        }
    },
    type: 'object',
    required: ['episode_number', 'episode_name', 'note', 'img', 'air_date', 'episode_rating', 'link_count'],
    title: 'EpisodeSummary'
} as const;

export const GenrePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['name', 'slug'],
    title: 'GenrePublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageUrlsSchema = {
    properties: {
        low: {
            type: 'string',
            title: 'Low'
        },
        mid: {
            type: 'string',
            title: 'Mid'
        },
        high: {
            type: 'string',
            title: 'High'
        }
    },
    type: 'object',
    required: ['low', 'mid', 'high'],
    title: 'ImageUrls'
} as const;

export const LinkPublicSchema = {
    properties: {
        quality: {
            type: 'string',
            title: 'Quality'
        },
        size: {
            type: 'string',
            title: 'Size'
        },
        servers: {
            items: {
                '$ref': '#/components/schemas/DownloadLink'
            },
            type: 'array',
            title: 'Servers'
        },
        only_hindi: {
            type: 'boolean',
            title: 'Only Hindi'
        },
        note: {
            type: 'string',
            title: 'Note'
        }
    },
    type: 'object',
    required: ['quality', 'size', 'servers', 'only_hindi', 'note'],
    title: 'LinkPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PackDetailSchema = {
    properties: {
        pack_name: {
            type: 'string',
            title: 'Pack Name'
        },
        start_ep: {
            type: 'integer',
            title: 'Start Ep'
        },
        end_ep: {
            type: 'integer',
            title: 'End Ep'
        },
        links: {
            items: {
                '$ref': '#/components/schemas/LinkPublic'
            },
            type: 'array',
            title: 'Links'
        },
        watch_servers: {
            items: {
                '$ref': '#/components/schemas/DownloadLink'
            },
            type: 'array',
            title: 'Watch Servers'
        }
    },
    type: 'object',
    required: ['pack_name', 'start_ep', 'end_ep', 'links', 'watch_servers'],
    title: 'PackDetail'
} as const;

export const PackSummarySchema = {
    properties: {
        pack_name: {
            type: 'string',
            title: 'Pack Name'
        },
        start_ep: {
            type: 'integer',
            title: 'Start Ep'
        },
        end_ep: {
            type: 'integer',
            title: 'End Ep'
        },
        link_count: {
            type: 'integer',
            title: 'Link Count'
        }
    },
    type: 'object',
    required: ['pack_name', 'start_ep', 'end_ep', 'link_count'],
    title: 'PackSummary'
} as const;

export const PostDetailSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        backdrop_img: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        status: {
            '$ref': '#/components/schemas/PostStatus'
        },
        sticky: {
            type: 'boolean',
            title: 'Sticky'
        },
        views: {
            type: 'integer',
            title: 'Views'
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags'
        },
        author: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AuthorPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        anime_slug: {
            type: 'string',
            title: 'Anime Slug'
        },
        anime_name: {
            type: 'string',
            title: 'Anime Name'
        },
        genres: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Genres'
        },
        anime: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AnimeDetail'
                },
                {
                    type: 'null'
                }
            ]
        },
        season: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SeasonDetail'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['slug', 'title', 'backdrop_img', 'status', 'sticky', 'views', 'last_updated', 'tags', 'author', 'anime_slug', 'anime_name', 'genres', 'anime', 'season'],
    title: 'PostDetail'
} as const;

export const PostListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PostSummary'
            },
            type: 'array',
            title: 'Data'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'page', 'limit', 'count'],
    title: 'PostListPublic'
} as const;

export const PostStatusSchema = {
    type: 'string',
    enum: ['ongoing', 'completed'],
    title: 'PostStatus'
} as const;

export const PostSummarySchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        backdrop_img: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        status: {
            '$ref': '#/components/schemas/PostStatus'
        },
        sticky: {
            type: 'boolean',
            title: 'Sticky'
        },
        views: {
            type: 'integer',
            title: 'Views'
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags'
        },
        comment_count: {
            type: 'integer',
            title: 'Comment Count'
        },
        author: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AuthorPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        anime_slug: {
            type: 'string',
            title: 'Anime Slug'
        },
        anime_name: {
            type: 'string',
            title: 'Anime Name'
        },
        season_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Season Number'
        },
        type: {
            type: 'string',
            title: 'Type'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'backdrop_img', 'status', 'sticky', 'views', 'last_updated', 'tags', 'comment_count', 'author', 'anime_slug', 'anime_name', 'season_number', 'type'],
    title: 'PostSummary'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReportRequestSchema = {
    properties: {
        shortener_id: {
            type: 'integer',
            title: 'Shortener Id'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['shortener_id'],
    title: 'ReportRequest'
} as const;

export const SeasonDetailSchema = {
    properties: {
        season_number: {
            type: 'integer',
            title: 'Season Number'
        },
        season_name: {
            type: 'string',
            title: 'Season Name'
        },
        poster: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        overview: {
            type: 'string',
            title: 'Overview'
        },
        rating: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Rating'
        },
        release_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Release Date'
        },
        total_episodes: {
            type: 'integer',
            title: 'Total Episodes'
        },
        dubs: {
            items: {
                '$ref': '#/components/schemas/SeasonDub'
            },
            type: 'array',
            title: 'Dubs'
        },
        episodes: {
            items: {
                '$ref': '#/components/schemas/EpisodeSummary'
            },
            type: 'array',
            title: 'Episodes'
        },
        packs: {
            items: {
                '$ref': '#/components/schemas/PackSummary'
            },
            type: 'array',
            title: 'Packs'
        }
    },
    type: 'object',
    required: ['season_number', 'season_name', 'poster', 'overview', 'rating', 'release_date', 'total_episodes', 'dubs', 'episodes', 'packs'],
    title: 'SeasonDetail'
} as const;

export const SeasonDubSchema = {
    properties: {
        platform: {
            type: 'string',
            title: 'Platform'
        },
        language: {
            type: 'string',
            title: 'Language'
        }
    },
    type: 'object',
    required: ['platform', 'language'],
    title: 'SeasonDub'
} as const;

export const SeasonSummarySchema = {
    properties: {
        season_number: {
            type: 'integer',
            title: 'Season Number'
        },
        season_name: {
            type: 'string',
            title: 'Season Name'
        },
        poster: {
            '$ref': '#/components/schemas/ImageUrls'
        },
        rating: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Rating'
        },
        episode_count: {
            type: 'integer',
            title: 'Episode Count'
        },
        pack_count: {
            type: 'integer',
            title: 'Pack Count'
        }
    },
    type: 'object',
    required: ['season_number', 'season_name', 'poster', 'rating', 'episode_count', 'pack_count'],
    title: 'SeasonSummary'
} as const;

export const ShortenerOptionSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        how_to_video_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'How To Video Url'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        already_solved: {
            type: 'boolean',
            title: 'Already Solved'
        },
        reported: {
            type: 'boolean',
            title: 'Reported'
        }
    },
    type: 'object',
    required: ['id', 'name', 'message', 'how_to_video_url', 'logo_url', 'already_solved', 'reported'],
    title: 'ShortenerOption'
} as const;

export const StartUnlockRequestSchema = {
    properties: {
        shortener_id: {
            type: 'integer',
            title: 'Shortener Id'
        }
    },
    type: 'object',
    required: ['shortener_id'],
    title: 'StartUnlockRequest'
} as const;

export const StartUnlockResponseSchema = {
    properties: {
        redirect_url: {
            type: 'string',
            title: 'Redirect Url'
        }
    },
    type: 'object',
    required: ['redirect_url'],
    title: 'StartUnlockResponse'
} as const;

export const TagPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['name', 'slug'],
    title: 'TagPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrendingAnimeItemSchema = {
    properties: {
        anime: {
            '$ref': '#/components/schemas/AnimeSummary'
        },
        views: {
            type: 'integer',
            title: 'Views'
        }
    },
    type: 'object',
    required: ['anime', 'views'],
    title: 'TrendingAnimeItem'
} as const;

export const TrendingAnimeListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TrendingAnimeItem'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TrendingAnimeList'
} as const;

export const TrendingEpisodeItemSchema = {
    properties: {
        anime_slug: {
            type: 'string',
            title: 'Anime Slug'
        },
        anime_name: {
            type: 'string',
            title: 'Anime Name'
        },
        season_number: {
            type: 'integer',
            title: 'Season Number'
        },
        episode: {
            '$ref': '#/components/schemas/EpisodeSummary'
        },
        views: {
            type: 'integer',
            title: 'Views'
        }
    },
    type: 'object',
    required: ['anime_slug', 'anime_name', 'season_number', 'episode', 'views'],
    title: 'TrendingEpisodeItem'
} as const;

export const TrendingEpisodeListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TrendingEpisodeItem'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TrendingEpisodeList'
} as const;

export const TrendingSeasonItemSchema = {
    properties: {
        anime_slug: {
            type: 'string',
            title: 'Anime Slug'
        },
        anime_name: {
            type: 'string',
            title: 'Anime Name'
        },
        season: {
            '$ref': '#/components/schemas/SeasonSummary'
        },
        views: {
            type: 'integer',
            title: 'Views'
        }
    },
    type: 'object',
    required: ['anime_slug', 'anime_name', 'season', 'views'],
    title: 'TrendingSeasonItem'
} as const;

export const TrendingSeasonListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TrendingSeasonItem'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TrendingSeasonList'
} as const;

export const UnlockStatusSchema = {
    properties: {
        unlocked: {
            type: 'boolean',
            title: 'Unlocked'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        solved: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solved'
        },
        required: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required'
        },
        shorteners: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ShortenerOption'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shorteners'
        }
    },
    type: 'object',
    required: ['unlocked'],
    title: 'UnlockStatus'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        access_scope: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AuthorAccessScope'
                },
                {
                    type: 'null'
                }
            ]
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        access_scope: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AuthorAccessScope'
                },
                {
                    type: 'null'
                }
            ]
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        access_scope: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AuthorAccessScope'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;