// This file is auto-generated by @hey-api/openapi-ts

export type AdminCommentListPublic = {
    data: Array<AdminCommentPublic>;
    count: number;
};

export type AdminCommentPublic = {
    id: number;
    post_id: number;
    post_slug: string;
    post_title: string;
    parent_id: (number | null);
    author_name: string;
    author_email: string;
    author_url: (string | null);
    body: string;
    created_at: string;
    status: CommentStatus;
};

export type AdminCommentStatusUpdate = {
    status: CommentStatus;
};

export type AdminStreamCommentListPublic = {
    data: Array<AdminStreamCommentPublic>;
    count: number;
};

export type AdminStreamCommentPublic = {
    id: number;
    content_id: number;
    parent_id: (number | null);
    author_name: string;
    author_email: string;
    author_url: (string | null);
    body: string;
    created_at: string;
    status: CommentStatus;
};

export type AnimeDetail = {
    content_id: number;
    slug: string;
    anime_name: string;
    type: string;
    poster: ImageUrls;
    backdrop: ImageUrls;
    overview: string;
    duration: number;
    rating: string;
    age_rating: string;
    genres: Array<(string)>;
    release_date: (string | null);
    seasons?: (Array<SeasonSummary> | null);
    links?: (Array<LinkPublic> | null);
    watch_servers?: (Array<DownloadLink> | null);
};

export type AnimeListPublic = {
    data: Array<AnimeSummary>;
    page: number;
    limit: number;
    count: number;
};

export type AnimeSummary = {
    slug: string;
    anime_name: string;
    type: string;
    poster: ImageUrls;
    rating: string;
    age_rating: string;
    genres: Array<(string)>;
    season_count: (number | null);
};

export type AuthorAccessScope = 'all' | 'ongoing' | 'access_list';

export type AuthorPublic = {
    display_name: string;
    slug: string;
    avatar_url: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CommentCreate = {
    author_name: string;
    author_email: string;
    author_url?: (string | null);
    body: string;
    parent_id?: (number | null);
};

export type CommentListPublic = {
    data: Array<CommentPublic>;
    page: number;
    limit: number;
    root_count: number;
    total_count: number;
};

export type CommentPublic = {
    id: number;
    parent_id: (number | null);
    author_name: string;
    author_url: (string | null);
    avatar_url: string;
    body: string;
    created_at: string;
};

export type CommentStatus = 'pending' | 'approved' | 'spam';

export type DownloadLink = {
    name: string;
    link_server_id: number;
    color: string;
};

export type EpisodeDetail = {
    content_id: number;
    episode_number: number;
    episode_name: (string | null);
    overview: (string | null);
    img: ImageUrls;
    air_date: (string | null);
    episode_runtime: (number | null);
    episode_rating: (string | null);
    links: Array<LinkPublic>;
    watch_servers: Array<DownloadLink>;
};

export type EpisodeSummary = {
    episode_number: number;
    episode_name: (string | null);
    note: (string | null);
    img: ImageUrls;
    air_date: (string | null);
    episode_rating: (string | null);
    link_count: number;
};

export type GenrePublic = {
    name: string;
    slug: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImageUrls = {
    low: string;
    mid: string;
    high: string;
};

export type LinkPublic = {
    quality: string;
    size: string;
    servers: Array<DownloadLink>;
    only_hindi: boolean;
    note: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PackDetail = {
    pack_name: string;
    start_ep: number;
    end_ep: number;
    links: Array<LinkPublic>;
    watch_servers: Array<DownloadLink>;
};

export type PackSummary = {
    pack_name: string;
    start_ep: number;
    end_ep: number;
    link_count: number;
};

export type PostDetail = {
    slug: string;
    title: string;
    backdrop_img: ImageUrls;
    status: PostStatus;
    sticky: boolean;
    views: number;
    last_updated: string;
    tags: Array<TagPublic>;
    author: (AuthorPublic | null);
    anime_slug: string;
    anime_name: string;
    genres: Array<(string)>;
    anime: (AnimeDetail | null);
    season: (SeasonDetail | null);
};

export type PostListPublic = {
    data: Array<PostSummary>;
    page: number;
    limit: number;
    count: number;
};

export type PostStatus = 'ongoing' | 'completed';

export type PostSummary = {
    slug: string;
    title: string;
    backdrop_img: ImageUrls;
    status: PostStatus;
    sticky: boolean;
    views: number;
    last_updated: string;
    tags: Array<TagPublic>;
    comment_count: number;
    author: (AuthorPublic | null);
    anime_slug: string;
    anime_name: string;
    season_number: (number | null);
    type: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReportRequest = {
    shortener_id: number;
    reason?: (string | null);
};

export type SeasonDetail = {
    season_number: number;
    season_name: string;
    poster: ImageUrls;
    overview: string;
    rating: string;
    release_date: (string | null);
    total_episodes: number;
    dubs: Array<SeasonDub>;
    episodes: Array<EpisodeSummary>;
    packs: Array<PackSummary>;
};

export type SeasonDub = {
    platform: string;
    language: string;
};

export type SeasonSummary = {
    season_number: number;
    season_name: string;
    poster: ImageUrls;
    rating: string;
    episode_count: number;
    pack_count: number;
};

export type ShortenerOption = {
    id: number;
    name: string;
    message: (string | null);
    how_to_video_url: (string | null);
    logo_url: (string | null);
    already_solved: boolean;
    reported: boolean;
};

export type StartUnlockRequest = {
    shortener_id: number;
};

export type StartUnlockResponse = {
    redirect_url: string;
};

export type TagPublic = {
    name: string;
    slug: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrendingAnimeItem = {
    anime: AnimeSummary;
    views: number;
};

export type TrendingAnimeList = {
    data: Array<TrendingAnimeItem>;
};

export type TrendingEpisodeItem = {
    anime_slug: string;
    anime_name: string;
    season_number: number;
    episode: EpisodeSummary;
    views: number;
};

export type TrendingEpisodeList = {
    data: Array<TrendingEpisodeItem>;
};

export type TrendingSeasonItem = {
    anime_slug: string;
    anime_name: string;
    season: SeasonSummary;
    views: number;
};

export type TrendingSeasonList = {
    data: Array<TrendingSeasonItem>;
};

export type UnlockStatus = {
    unlocked: boolean;
    url?: (string | null);
    solved?: (number | null);
    required?: (number | null);
    shorteners?: (Array<ShortenerOption> | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    access_scope?: (AuthorAccessScope | null);
    password?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    access_scope?: (AuthorAccessScope | null);
    id: string;
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
    access_scope?: (AuthorAccessScope | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminListCommentsData = {
    limit?: number;
    skip?: number;
    status?: (CommentStatus | null);
};

export type AdminListCommentsResponse = (AdminCommentListPublic);

export type AdminUpdateCommentStatusData = {
    commentId: number;
    requestBody: AdminCommentStatusUpdate;
};

export type AdminUpdateCommentStatusResponse = (AdminCommentPublic);

export type AdminDeleteCommentData = {
    commentId: number;
};

export type AdminDeleteCommentResponse = (void);

export type AdminListStreamCommentsData = {
    limit?: number;
    skip?: number;
    status?: (CommentStatus | null);
};

export type AdminListStreamCommentsResponse = (AdminStreamCommentListPublic);

export type AdminUpdateStreamCommentStatusData = {
    commentId: number;
    requestBody: AdminCommentStatusUpdate;
};

export type AdminUpdateStreamCommentStatusResponse = (AdminStreamCommentPublic);

export type AdminDeleteStreamCommentData = {
    commentId: number;
};

export type AdminDeleteStreamCommentResponse = (void);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PublicListAnimeData = {
    genre?: (string | null);
    limit?: number;
    page?: number;
    q?: (string | null);
    sort?: 'rating' | 'latest' | 'name';
    type?: (string | null);
};

export type PublicListAnimeResponse = (AnimeListPublic);

export type PublicReadAnimeData = {
    slug: string;
};

export type PublicReadAnimeResponse = (AnimeDetail);

export type PublicReadSeasonData = {
    seasonNumber: number;
    slug: string;
};

export type PublicReadSeasonResponse = (SeasonDetail);

export type PublicReadEpisodeData = {
    episodeNumber: number;
    seasonNumber: number;
    slug: string;
};

export type PublicReadEpisodeResponse = (EpisodeDetail);

export type PublicReadPackData = {
    episodeRange: string;
    seasonNumber: number;
    slug: string;
};

export type PublicReadPackResponse = (PackDetail);

export type PublicListPostsData = {
    author?: (string | null);
    genre?: (string | null);
    limit?: number;
    page?: number;
    q?: (string | null);
    sort?: 'latest' | 'popular';
    status?: (PostStatus | null);
    tag?: (string | null);
    type?: ('movie' | 'tv' | null);
};

export type PublicListPostsResponse = (PostListPublic);

export type PublicReadPostData = {
    slug: string;
};

export type PublicReadPostResponse = (PostDetail);

export type PublicListCommentsData = {
    limit?: number;
    page?: number;
    slug: string;
};

export type PublicListCommentsResponse = (CommentListPublic);

export type PublicCreateCommentData = {
    requestBody: CommentCreate;
    slug: string;
};

export type PublicCreateCommentResponse = (CommentPublic);

export type PublicUnlockCallbackData = {
    token: string;
};

export type PublicUnlockCallbackResponse = (unknown);

export type PublicUnlockStatusData = {
    linkServerId: number;
};

export type PublicUnlockStatusResponse = (UnlockStatus);

export type PublicStartUnlockData = {
    linkServerId: number;
    requestBody: StartUnlockRequest;
};

export type PublicStartUnlockResponse = (StartUnlockResponse);

export type PublicReportShortenerData = {
    linkServerId: number;
    requestBody: ReportRequest;
};

export type PublicReportShortenerResponse = (Message);

export type PublicTrackViewData = {
    contentId: number;
};

export type PublicTrackViewResponse = (Message);

export type PublicTrendingAnimeData = {
    limit?: number;
    window?: 'today' | 'week' | 'month' | 'all';
};

export type PublicTrendingAnimeResponse = (TrendingAnimeList);

export type PublicTrendingSeasonsData = {
    limit?: number;
    window?: 'today' | 'week' | 'month' | 'all';
};

export type PublicTrendingSeasonsResponse = (TrendingSeasonList);

export type PublicTrendingEpisodesData = {
    limit?: number;
    window?: 'today' | 'week' | 'month' | 'all';
};

export type PublicTrendingEpisodesResponse = (TrendingEpisodeList);

export type PublicListContentCommentsData = {
    contentId: number;
};

export type PublicListContentCommentsResponse = (Array<CommentPublic>);

export type PublicCreateContentCommentData = {
    contentId: number;
    requestBody: CommentCreate;
};

export type PublicCreateContentCommentResponse = (CommentPublic);

export type PublicListTagsResponse = (Array<TagPublic>);

export type PublicListGenresResponse = (Array<GenrePublic>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);