"""add stream comments table

Revision ID: 0ece43d8b5d5
Revises: b376528c09a2
Create Date: 2026-07-17 10:41:45.257127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0ece43d8b5d5'
down_revision = 'b376528c09a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('author_email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('author_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'SPAM', name='commentstatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['stream_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_comments_content_id'), 'stream_comments', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_comments_content_id'), table_name='stream_comments')
    op.drop_table('stream_comments')
    # ### end Alembic commands ###
