"""create deadbase tables

Revision ID: 4ec55cb094af
Revises: fe56fa70289e
Create Date: 2026-07-09 18:19:50.270586

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4ec55cb094af'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_ratings',
    sa.Column('age_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('age_name', sa.String(length=50), nullable=False),
    sa.Column('age_des', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('age_id', name='idx_17146_primary')
    )
    op.create_table('content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.Enum('movie', 'pack', 'episode', name='content_content_type'), nullable=False),
    sa.Column('respective_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='idx_17182_primary')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('genre_name', sa.String(length=20), nullable=False),
    sa.Column('genre_sid', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('genre_id', name='idx_17205_primary')
    )
    op.create_index('idx_17205_genre_sid', 'genres', ['genre_sid'], unique=True)
    op.create_table('languages',
    sa.Column('language_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('language_sid', sa.String(length=20), nullable=False),
    sa.Column('language_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('language_id', name='idx_17213_primary')
    )
    op.create_index('idx_17213_language_sid', 'languages', ['language_sid'], unique=True)
    op.create_table('ott_platforms',
    sa.Column('ott_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ott_sid', sa.String(length=20), nullable=False),
    sa.Column('ott_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ott_id', name='idx_17255_primary')
    )
    op.create_index('idx_17255_ott_sid', 'ott_platforms', ['ott_sid'], unique=True)
    op.create_table('qualities',
    sa.Column('quality_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quality_resolution', sa.BigInteger(), nullable=False),
    sa.Column('is_hevc', sa.Boolean(), nullable=False),
    sa.Column('is_hq', sa.Boolean(), nullable=False),
    sa.Column('quality_order', sa.BigInteger(), nullable=False),
    sa.Column('quality_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('quality_id', name='idx_17274_primary')
    )
    op.create_table('server_info',
    sa.Column('server_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('server_sid', sa.String(length=20), nullable=False),
    sa.Column('server_name', sa.String(length=30), nullable=False),
    sa.Column('server_order', sa.BigInteger(), nullable=False),
    sa.Column('server_domain', sa.String(length=50), nullable=False),
    sa.Column('api', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('server_id', name='idx_17309_primary')
    )
    op.create_index('idx_17309_idx_server_sid', 'server_info', ['server_sid'], unique=True)
    op.create_table('source',
    sa.Column('source_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('poster', sa.String(length=10), nullable=False),
    sa.Column('poster_mid', sa.String(length=10), nullable=False),
    sa.Column('backdrop', sa.String(length=10), nullable=False),
    sa.Column('poster_small', sa.String(length=10), nullable=False),
    sa.Column('low', sa.String(length=10), nullable=False),
    sa.Column('backdrop_mid', sa.String(length=10), nullable=False),
    sa.Column('backdrop_high', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('source_id', name='idx_17323_primary')
    )
    op.create_table('animes',
    sa.Column('anime_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('anime_name', sa.String(length=255), nullable=False),
    sa.Column('backdrop_source', sa.Enum('tmdb', 'local', name='animes_backdrop_source'), nullable=False),
    sa.Column('backdrop_img', sa.String(length=255), nullable=False),
    sa.Column('poster_source', sa.Enum('tmdb', 'local', 'url', name='animes_poster_source'), nullable=False),
    sa.Column('poster_img', sa.String(length=255), nullable=False),
    sa.Column('age_id', sa.BigInteger(), server_default=sa.text("'3'::bigint"), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('links_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('anime_tmdb_id', sa.BigInteger(), nullable=True),
    sa.Column('anime_rel_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['age_id'], ['age_ratings.age_id'], name='age', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='animes_ibfk_2', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('anime_id', name='idx_17154_primary')
    )
    op.create_index('idx_17154_age', 'animes', ['age_id'], unique=False)
    op.create_index('idx_17154_anime_name', 'animes', ['anime_name'], unique=False)
    op.create_index('idx_17154_content_id', 'animes', ['content_id'], unique=True)
    op.create_index('idx_17154_slug', 'animes', ['slug'], unique=True)
    op.create_index('idx_17154_slug_2', 'animes', ['slug'], unique=False)
    op.create_index('idx_17154_slug_3', 'animes', ['slug'], unique=False)
    op.create_table('links',
    sa.Column('link_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=250), nullable=False),
    sa.Column('is_live', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('gdrive_email', sa.String(length=90), nullable=False),
    sa.Column('gdriveid', sa.String(length=33), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('mimetype', sa.String(length=30), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('only_hindi', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('added_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('size', sa.Numeric(), nullable=True),
    sa.Column('quality_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['quality_id'], ['qualities.quality_id'], name='links_ibfk_1', onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('link_id', name='idx_17221_primary')
    )
    op.create_index('idx_17221_gdriveid', 'links', ['gdriveid'], unique=True)
    op.create_index('idx_17221_idx_linksinfo_filter', 'links', ['is_live', 'type', 'link_id'], unique=False)
    op.create_index('idx_17221_quality', 'links', ['quality_id'], unique=False)
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.anime_id'], name='anime_genres_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], name='anime_genres_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id', name='idx_17176_primary')
    )
    op.create_index('idx_17176_genre_id', 'anime_genres', ['genre_id'], unique=False)
    op.create_table('link_servers',
    sa.Column('ser_link_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('is_uploaded', sa.BigInteger(), server_default=sa.text("'0'::bigint"), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.link_id'], name='link_servers_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['server_info.server_id'], name='link_servers_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ser_link_id', name='idx_17244_primary')
    )
    op.create_index('idx_17244_idx_serverslinks_linkid_serverid_slug', 'link_servers', ['link_id', 'server_id', 'slug'], unique=False)
    op.create_index('idx_17244_link_id', 'link_servers', ['link_id', 'server_id'], unique=True)
    op.create_index('idx_17244_link_id_2', 'link_servers', ['link_id'], unique=False)
    op.create_index('idx_17244_servers_links_ibfk_1', 'link_servers', ['server_id'], unique=False)
    op.create_table('seasons',
    sa.Column('season_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('anime_id', sa.BigInteger(), nullable=False),
    sa.Column('season_number', sa.BigInteger(), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=False),
    sa.Column('total_episodes', sa.BigInteger(), nullable=False),
    sa.Column('season_overview', sa.Text(), nullable=False),
    sa.Column('poster_source', sa.Enum('tmdb', 'local', name='seasons_poster_source'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('season_tmdb_id', sa.String(length=20), server_default=sa.text('NULL::character varying'), nullable=True),
    sa.Column('season_rel_date', sa.Date(), nullable=True),
    sa.Column('poster_img', sa.String(length=255), server_default=sa.text('NULL::character varying'), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.anime_id'], name='seasons_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id', name='idx_17285_primary')
    )
    op.create_index('idx_17285_anime_id', 'seasons', ['anime_id', 'season_number'], unique=True)
    op.create_table('episodes',
    sa.Column('episode_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('episode_number', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('episode_tmdb_id', sa.String(length=20), server_default=sa.text('NULL::character varying'), nullable=True),
    sa.Column('episode_name', sa.String(length=150), server_default=sa.text('NULL::character varying'), nullable=True),
    sa.Column('note', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('episode_runtime', sa.BigInteger(), nullable=True),
    sa.Column('episode_rating', sa.Numeric(precision=4, scale=2), server_default=sa.text('NULL::numeric'), nullable=True),
    sa.Column('img', sa.String(length=255), server_default=sa.text('NULL::character varying'), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='episodes_ibfk_2', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name='episodes_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', name='idx_17189_primary')
    )
    op.create_index('idx_17189_content_id', 'episodes', ['content_id'], unique=True)
    op.create_index('idx_17189_season_id', 'episodes', ['season_id', 'episode_number'], unique=True)
    op.create_table('packs',
    sa.Column('pack_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('pack_name', sa.String(length=100), nullable=False),
    sa.Column('start_ep', sa.BigInteger(), nullable=False),
    sa.Column('end_ep', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='packs_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name='packs_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pack_id', name='idx_17263_primary')
    )
    op.create_index('idx_17263_content_id', 'packs', ['content_id'], unique=False)
    op.create_index('idx_17263_my_season_id', 'packs', ['season_id'], unique=False)
    op.create_table('season_dubs',
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('ott_id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], name='season_dubs_ibfk_2', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ott_id'], ['ott_platforms.ott_id'], name='season_dubs_ibfk_3', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name='season_dubs_ibfk_1', onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_index('idx_17302_language_id', 'season_dubs', ['language_id'], unique=False)
    op.create_index('idx_17302_ott_id', 'season_dubs', ['ott_id'], unique=False)
    op.create_index('idx_17302_season_id', 'season_dubs', ['season_id', 'ott_id', 'language_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_17302_season_id', table_name='season_dubs')
    op.drop_index('idx_17302_ott_id', table_name='season_dubs')
    op.drop_index('idx_17302_language_id', table_name='season_dubs')
    op.drop_table('season_dubs')
    op.drop_index('idx_17263_my_season_id', table_name='packs')
    op.drop_index('idx_17263_content_id', table_name='packs')
    op.drop_table('packs')
    op.drop_index('idx_17189_season_id', table_name='episodes')
    op.drop_index('idx_17189_content_id', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('idx_17285_anime_id', table_name='seasons')
    op.drop_table('seasons')
    op.drop_index('idx_17244_servers_links_ibfk_1', table_name='link_servers')
    op.drop_index('idx_17244_link_id_2', table_name='link_servers')
    op.drop_index('idx_17244_link_id', table_name='link_servers')
    op.drop_index('idx_17244_idx_serverslinks_linkid_serverid_slug', table_name='link_servers')
    op.drop_table('link_servers')
    op.drop_index('idx_17176_genre_id', table_name='anime_genres')
    op.drop_table('anime_genres')
    op.drop_index('idx_17221_quality', table_name='links')
    op.drop_index('idx_17221_idx_linksinfo_filter', table_name='links')
    op.drop_index('idx_17221_gdriveid', table_name='links')
    op.drop_table('links')
    op.drop_index('idx_17154_slug_3', table_name='animes')
    op.drop_index('idx_17154_slug_2', table_name='animes')
    op.drop_index('idx_17154_slug', table_name='animes')
    op.drop_index('idx_17154_content_id', table_name='animes')
    op.drop_index('idx_17154_anime_name', table_name='animes')
    op.drop_index('idx_17154_age', table_name='animes')
    op.drop_table('animes')
    op.drop_table('source')
    op.drop_index('idx_17309_idx_server_sid', table_name='server_info')
    op.drop_table('server_info')
    op.drop_table('qualities')
    op.drop_index('idx_17255_ott_sid', table_name='ott_platforms')
    op.drop_table('ott_platforms')
    op.drop_index('idx_17213_language_sid', table_name='languages')
    op.drop_table('languages')
    op.drop_index('idx_17205_genre_sid', table_name='genres')
    op.drop_table('genres')
    op.drop_table('content')
    op.drop_table('age_ratings')
    # ### end Alembic commands ###
