"""add author access scope

Revision ID: 60c101526c5d
Revises: ca64ded3153e
Create Date: 2026-07-18 20:32:58.982211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '60c101526c5d'
down_revision = 'ca64ded3153e'
branch_labels = None
depends_on = None


author_access_scope_enum = sa.Enum(
    'ALL', 'ONGOING', 'ACCESS_LIST', name='authoraccessscope'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_anime_access',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.anime_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'anime_id')
    )
    # op.add_column below needs the enum type to already exist - unlike
    # create_table, ALTER TABLE ADD COLUMN doesn't auto-create it.
    author_access_scope_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('access_scope', author_access_scope_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_scope')
    author_access_scope_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_table('author_anime_access')
    # ### end Alembic commands ###
