"""add logo_url to link_shorteners

Revision ID: 6693fa14a1c3
Revises: 0ece43d8b5d5
Create Date: 2026-07-17 12:29:15.574308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6693fa14a1c3'
down_revision = '0ece43d8b5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_shorteners', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_shorteners', 'logo_url')
    # ### end Alembic commands ###
