"""add view monthly rollup tables

Revision ID: 6c04f866c475
Revises: c94697fc6326
Create Date: 2026-07-20 12:11:09.443392

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c04f866c475'
down_revision = 'c94697fc6326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_view_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'year', 'month', name='content_view_monthly_content_ym_key')
    )
    op.create_index(op.f('ix_content_view_monthly_content_id'), 'content_view_monthly', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_view_monthly_year'), 'content_view_monthly', ['year'], unique=False)
    op.create_table('anime_view_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.anime_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'year', 'month', name='anime_view_monthly_anime_ym_key')
    )
    op.create_index(op.f('ix_anime_view_monthly_anime_id'), 'anime_view_monthly', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_view_monthly_year'), 'anime_view_monthly', ['year'], unique=False)
    op.create_table('season_view_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'year', 'month', name='season_view_monthly_season_ym_key')
    )
    op.create_index(op.f('ix_season_view_monthly_season_id'), 'season_view_monthly', ['season_id'], unique=False)
    op.create_index(op.f('ix_season_view_monthly_year'), 'season_view_monthly', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_view_monthly_year'), table_name='season_view_monthly')
    op.drop_index(op.f('ix_season_view_monthly_season_id'), table_name='season_view_monthly')
    op.drop_table('season_view_monthly')
    op.drop_index(op.f('ix_anime_view_monthly_year'), table_name='anime_view_monthly')
    op.drop_index(op.f('ix_anime_view_monthly_anime_id'), table_name='anime_view_monthly')
    op.drop_table('anime_view_monthly')
    op.drop_index(op.f('ix_content_view_monthly_year'), table_name='content_view_monthly')
    op.drop_index(op.f('ix_content_view_monthly_content_id'), table_name='content_view_monthly')
    op.drop_table('content_view_monthly')
    # ### end Alembic commands ###
