"""add fk constraint on links content_id

Revision ID: 6c88690b15ea
Revises: b79b5cfa5762
Create Date: 2026-07-15 22:31:30.309231

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c88690b15ea'
down_revision = 'b79b5cfa5762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('links_ibfk_2', 'links', 'content', ['content_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('links_ibfk_2', 'links', type_='foreignkey')
    # ### end Alembic commands ###
