"""add link shortener unlock gate and download analytics tables

Revision ID: 6dd2403b5b1a
Revises: 8158de474ec9
Create Date: 2026-07-17 02:20:02.382550

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6dd2403b5b1a'
down_revision = '8158de474ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_shorteners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('api_url_template', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('quick_url_template', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('how_to_video_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('unlock_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required_solves', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='unlock_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_server_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('via_shortener_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_server_id'], ['link_servers.ser_link_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['via_shortener_id'], ['link_shorteners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_events_link_server_id'), 'download_events', ['link_server_id'], unique=False)
    op.create_index(op.f('ix_download_events_occurred_at'), 'download_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_download_events_via_shortener_id'), 'download_events', ['via_shortener_id'], unique=False)
    op.create_index(op.f('ix_download_events_visitor_id'), 'download_events', ['visitor_id'], unique=False)
    op.create_table('shortener_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('shortener_id', sa.Integer(), nullable=False),
    sa.Column('link_server_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['link_server_id'], ['link_servers.ser_link_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shortener_id'], ['link_shorteners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortener_attempts_link_server_id'), 'shortener_attempts', ['link_server_id'], unique=False)
    op.create_index(op.f('ix_shortener_attempts_shortener_id'), 'shortener_attempts', ['shortener_id'], unique=False)
    op.create_index(op.f('ix_shortener_attempts_token'), 'shortener_attempts', ['token'], unique=True)
    op.create_index(op.f('ix_shortener_attempts_visitor_id'), 'shortener_attempts', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortener_attempts_visitor_id'), table_name='shortener_attempts')
    op.drop_index(op.f('ix_shortener_attempts_token'), table_name='shortener_attempts')
    op.drop_index(op.f('ix_shortener_attempts_shortener_id'), table_name='shortener_attempts')
    op.drop_index(op.f('ix_shortener_attempts_link_server_id'), table_name='shortener_attempts')
    op.drop_table('shortener_attempts')
    op.drop_index(op.f('ix_download_events_visitor_id'), table_name='download_events')
    op.drop_index(op.f('ix_download_events_via_shortener_id'), table_name='download_events')
    op.drop_index(op.f('ix_download_events_occurred_at'), table_name='download_events')
    op.drop_index(op.f('ix_download_events_link_server_id'), table_name='download_events')
    op.drop_table('download_events')
    op.drop_table('unlock_config')
    op.drop_table('link_shorteners')
    # ### end Alembic commands ###
