"""add report_threshold to unlock_config

Revision ID: 8da818192210
Revises: 6dd2403b5b1a
Create Date: 2026-07-17 02:41:18.256213

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8da818192210'
down_revision = '6dd2403b5b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'unlock_config',
        sa.Column('report_threshold', sa.Integer(), nullable=False, server_default='5'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unlock_config', 'report_threshold')
    # ### end Alembic commands ###
