"""add view tracking and trending rollup tables

Revision ID: b376528c09a2
Revises: 8da818192210
Create Date: 2026-07-17 09:36:10.031356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b376528c09a2'
down_revision = '8da818192210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_view_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'view_date', name='content_view_daily_content_date_key')
    )
    op.create_index(op.f('ix_content_view_daily_content_id'), 'content_view_daily', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_view_daily_view_date'), 'content_view_daily', ['view_date'], unique=False)
    op.create_table('content_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rolled_up', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', 'content_id', 'view_date', name='content_views_visitor_content_date_key')
    )
    op.create_index(op.f('ix_content_views_content_id'), 'content_views', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_views_rolled_up'), 'content_views', ['rolled_up'], unique=False)
    op.create_index(op.f('ix_content_views_view_date'), 'content_views', ['view_date'], unique=False)
    op.create_index(op.f('ix_content_views_visitor_id'), 'content_views', ['visitor_id'], unique=False)
    op.create_table('anime_view_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.anime_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'view_date', name='anime_view_daily_anime_date_key')
    )
    op.create_index(op.f('ix_anime_view_daily_anime_id'), 'anime_view_daily', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_view_daily_view_date'), 'anime_view_daily', ['view_date'], unique=False)
    op.create_table('season_view_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'view_date', name='season_view_daily_season_date_key')
    )
    op.create_index(op.f('ix_season_view_daily_season_id'), 'season_view_daily', ['season_id'], unique=False)
    op.create_index(op.f('ix_season_view_daily_view_date'), 'season_view_daily', ['view_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_view_daily_view_date'), table_name='season_view_daily')
    op.drop_index(op.f('ix_season_view_daily_season_id'), table_name='season_view_daily')
    op.drop_table('season_view_daily')
    op.drop_index(op.f('ix_anime_view_daily_view_date'), table_name='anime_view_daily')
    op.drop_index(op.f('ix_anime_view_daily_anime_id'), table_name='anime_view_daily')
    op.drop_table('anime_view_daily')
    op.drop_index(op.f('ix_content_views_visitor_id'), table_name='content_views')
    op.drop_index(op.f('ix_content_views_view_date'), table_name='content_views')
    op.drop_index(op.f('ix_content_views_rolled_up'), table_name='content_views')
    op.drop_index(op.f('ix_content_views_content_id'), table_name='content_views')
    op.drop_table('content_views')
    op.drop_index(op.f('ix_content_view_daily_view_date'), table_name='content_view_daily')
    op.drop_index(op.f('ix_content_view_daily_content_id'), table_name='content_view_daily')
    op.drop_table('content_view_daily')
    # ### end Alembic commands ###
