"""add upload_enabled to server_info

Revision ID: b4212d3c656f
Revises: e67b5bd2997c
Create Date: 2026-07-20 13:34:08.972851

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4212d3c656f'
down_revision = 'e67b5bd2997c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_info', sa.Column('upload_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_info', 'upload_enabled')
    # ### end Alembic commands ###
