"""add download stats tables

Revision ID: c94697fc6326
Revises: 55f6ab7a9c91
Create Date: 2026-07-20 11:40:16.236485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c94697fc6326'
down_revision = '55f6ab7a9c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_download_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('download_date', sa.Date(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'download_date', name='content_download_daily_content_date_key')
    )
    op.create_index(op.f('ix_content_download_daily_content_id'), 'content_download_daily', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_download_daily_download_date'), 'content_download_daily', ['download_date'], unique=False)
    op.create_table('content_download_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'year', 'month', name='content_download_monthly_content_ym_key')
    )
    op.create_index(op.f('ix_content_download_monthly_content_id'), 'content_download_monthly', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_download_monthly_year'), 'content_download_monthly', ['year'], unique=False)
    op.create_table('server_download_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('download_date', sa.Date(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_info.server_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'download_date', name='server_download_daily_server_date_key')
    )
    op.create_index(op.f('ix_server_download_daily_download_date'), 'server_download_daily', ['download_date'], unique=False)
    op.create_index(op.f('ix_server_download_daily_server_id'), 'server_download_daily', ['server_id'], unique=False)
    op.create_table('shortener_funnel_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortener_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('solved', sa.Integer(), nullable=False),
    sa.Column('reported', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shortener_id'], ['link_shorteners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortener_id', 'stat_date', name='shortener_funnel_daily_shortener_date_key')
    )
    op.create_index(op.f('ix_shortener_funnel_daily_shortener_id'), 'shortener_funnel_daily', ['shortener_id'], unique=False)
    op.create_index(op.f('ix_shortener_funnel_daily_stat_date'), 'shortener_funnel_daily', ['stat_date'], unique=False)
    # content_id is nullable at first so existing rows don't violate NOT NULL
    # before they're backfilled - resolved via link_server -> link -> content,
    # the same hop resolve_anime_id_for_content already does for other
    # content-bearing tables.
    op.add_column('download_events', sa.Column('content_id', sa.Integer(), nullable=True))
    op.add_column(
        'download_events',
        sa.Column('rolled_up', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.execute(
        """
        UPDATE download_events
        SET content_id = links.content_id
        FROM link_servers
        JOIN links ON links.link_id = link_servers.link_id
        WHERE link_servers.ser_link_id = download_events.link_server_id
        """
    )
    op.alter_column('download_events', 'content_id', nullable=False)
    op.create_index(op.f('ix_download_events_content_id'), 'download_events', ['content_id'], unique=False)
    op.create_index(op.f('ix_download_events_rolled_up'), 'download_events', ['rolled_up'], unique=False)
    op.create_foreign_key(None, 'download_events', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'download_events', type_='foreignkey')
    op.drop_index(op.f('ix_download_events_rolled_up'), table_name='download_events')
    op.drop_index(op.f('ix_download_events_content_id'), table_name='download_events')
    op.drop_column('download_events', 'rolled_up')
    op.drop_column('download_events', 'content_id')
    op.drop_index(op.f('ix_shortener_funnel_daily_stat_date'), table_name='shortener_funnel_daily')
    op.drop_index(op.f('ix_shortener_funnel_daily_shortener_id'), table_name='shortener_funnel_daily')
    op.drop_table('shortener_funnel_daily')
    op.drop_index(op.f('ix_server_download_daily_server_id'), table_name='server_download_daily')
    op.drop_index(op.f('ix_server_download_daily_download_date'), table_name='server_download_daily')
    op.drop_table('server_download_daily')
    op.drop_index(op.f('ix_content_download_monthly_year'), table_name='content_download_monthly')
    op.drop_index(op.f('ix_content_download_monthly_content_id'), table_name='content_download_monthly')
    op.drop_table('content_download_monthly')
    op.drop_index(op.f('ix_content_download_daily_download_date'), table_name='content_download_daily')
    op.drop_index(op.f('ix_content_download_daily_content_id'), table_name='content_download_daily')
    op.drop_table('content_download_daily')
    # ### end Alembic commands ###
