"""add upload job tracking to link_servers

Revision ID: d4ef0a5fe899
Revises: 6c04f866c475
Create Date: 2026-07-20 12:48:59.801653

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd4ef0a5fe899'
down_revision = '6c04f866c475'
branch_labels = None
depends_on = None

link_server_status_enum = postgresql.ENUM(
    'pending', 'success', 'failed', name='link_server_status'
)


def upgrade():
    link_server_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'link_servers',
        sa.Column(
            'status',
            postgresql.ENUM(
                'pending', 'success', 'failed', name='link_server_status', create_type=False
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
    )
    op.add_column('link_servers', sa.Column('attempt_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('link_servers', sa.Column('last_error', sa.String(length=500), nullable=True))
    op.add_column('link_servers', sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('link_servers', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('link_servers', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_link_servers_next_attempt_at'), 'link_servers', ['next_attempt_at'], unique=False)
    op.drop_column('link_servers', 'is_uploaded')
    # ### end Alembic commands ###

    # Normalize legacy '' placeholders to NULL - going forward a pending/
    # failed row always has slug=NULL, never ''.
    op.execute("UPDATE link_servers SET slug = NULL WHERE slug = ''")

    # Existing rows with a real slug are already-successful legacy uploads,
    # not new pending jobs - without this the upload queue would treat all
    # ~421k of them as needing (re)upload.
    op.execute("UPDATE link_servers SET status = 'success' WHERE slug IS NOT NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_servers', sa.Column('is_uploaded', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_link_servers_next_attempt_at'), table_name='link_servers')
    op.alter_column('link_servers', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('link_servers', 'next_attempt_at')
    op.drop_column('link_servers', 'last_attempted_at')
    op.drop_column('link_servers', 'last_error')
    op.drop_column('link_servers', 'attempt_count')
    op.drop_column('link_servers', 'status')
    # ### end Alembic commands ###
    link_server_status_enum.drop(op.get_bind(), checkfirst=True)
