"""add api_domain to server_info

Revision ID: e67b5bd2997c
Revises: d4ef0a5fe899
Create Date: 2026-07-20 13:01:42.997163

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e67b5bd2997c'
down_revision = 'd4ef0a5fe899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_info', sa.Column('api_domain', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_info', 'api_domain')
    # ### end Alembic commands ###
