"""add unique constraint on packs season_id start_ep end_ep

Revision ID: ea4a352803ea
Revises: 6c88690b15ea
Create Date: 2026-07-16 12:39:43.604645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea4a352803ea'
down_revision = '6c88690b15ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_packs_season_id_start_ep_end_ep', 'packs', ['season_id', 'start_ep', 'end_ep'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_packs_season_id_start_ep_end_ep', table_name='packs')
    # ### end Alembic commands ###
