/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as PackSlugRangeRouteImport } from './routes/pack.$slug.$range'
import { Route as EpisodeSlugEpRouteImport } from './routes/episode.$slug.$ep'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PackSlugRangeRoute = PackSlugRangeRouteImport.update({
  id: '/pack/$slug/$range',
  path: '/pack/$slug/$range',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeSlugEpRoute = EpisodeSlugEpRouteImport.update({
  id: '/episode/$slug/$ep',
  path: '/episode/$slug/$ep',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trending': typeof TrendingRoute
  '/unlock': typeof UnlockRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/episode/$slug/$ep': typeof EpisodeSlugEpRoute
  '/pack/$slug/$range': typeof PackSlugRangeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trending': typeof TrendingRoute
  '/unlock': typeof UnlockRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/episode/$slug/$ep': typeof EpisodeSlugEpRoute
  '/pack/$slug/$range': typeof PackSlugRangeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trending': typeof TrendingRoute
  '/unlock': typeof UnlockRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/episode/$slug/$ep': typeof EpisodeSlugEpRoute
  '/pack/$slug/$range': typeof PackSlugRangeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trending'
    | '/unlock'
    | '/movie/$slug'
    | '/episode/$slug/$ep'
    | '/pack/$slug/$range'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trending'
    | '/unlock'
    | '/movie/$slug'
    | '/episode/$slug/$ep'
    | '/pack/$slug/$range'
  id:
    | '__root__'
    | '/'
    | '/trending'
    | '/unlock'
    | '/movie/$slug'
    | '/episode/$slug/$ep'
    | '/pack/$slug/$range'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrendingRoute: typeof TrendingRoute
  UnlockRoute: typeof UnlockRoute
  MovieSlugRoute: typeof MovieSlugRoute
  EpisodeSlugEpRoute: typeof EpisodeSlugEpRoute
  PackSlugRangeRoute: typeof PackSlugRangeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack/$slug/$range': {
      id: '/pack/$slug/$range'
      path: '/pack/$slug/$range'
      fullPath: '/pack/$slug/$range'
      preLoaderRoute: typeof PackSlugRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$slug/$ep': {
      id: '/episode/$slug/$ep'
      path: '/episode/$slug/$ep'
      fullPath: '/episode/$slug/$ep'
      preLoaderRoute: typeof EpisodeSlugEpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrendingRoute: TrendingRoute,
  UnlockRoute: UnlockRoute,
  MovieSlugRoute: MovieSlugRoute,
  EpisodeSlugEpRoute: EpisodeSlugEpRoute,
  PackSlugRangeRoute: PackSlugRangeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
