/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminPeopleRouteImport } from './routes/_layout/admin.people'
import { Route as LayoutAdminCommentsRouteImport } from './routes/_layout/admin.comments'
import { Route as LayoutAdminContentIndexRouteImport } from './routes/_layout/admin/content/index'
import { Route as LayoutAdminContentNewRouteImport } from './routes/_layout/admin/content/new'
import { Route as LayoutAdminContentAnimeIdIndexRouteImport } from './routes/_layout/admin/content/$animeId/index'
import { Route as LayoutAdminContentAnimeIdSeasonsNewRouteImport } from './routes/_layout/admin/content/$animeId/seasons/new'
import { Route as LayoutAdminContentAnimeIdSeasonsSeasonIdRouteImport } from './routes/_layout/admin/content/$animeId/seasons/$seasonId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminPeopleRoute = LayoutAdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminCommentsRoute = LayoutAdminCommentsRouteImport.update({
  id: '/admin/comments',
  path: '/admin/comments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminContentIndexRoute = LayoutAdminContentIndexRouteImport.update({
  id: '/admin/content/',
  path: '/admin/content/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminContentNewRoute = LayoutAdminContentNewRouteImport.update({
  id: '/admin/content/new',
  path: '/admin/content/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminContentAnimeIdIndexRoute =
  LayoutAdminContentAnimeIdIndexRouteImport.update({
    id: '/admin/content/$animeId/',
    path: '/admin/content/$animeId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminContentAnimeIdSeasonsNewRoute =
  LayoutAdminContentAnimeIdSeasonsNewRouteImport.update({
    id: '/admin/content/$animeId/seasons/new',
    path: '/admin/content/$animeId/seasons/new',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminContentAnimeIdSeasonsSeasonIdRoute =
  LayoutAdminContentAnimeIdSeasonsSeasonIdRouteImport.update({
    id: '/admin/content/$animeId/seasons/$seasonId',
    path: '/admin/content/$animeId/seasons/$seasonId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof LayoutSettingsRoute
  '/admin/comments': typeof LayoutAdminCommentsRoute
  '/admin/people': typeof LayoutAdminPeopleRoute
  '/admin/content/new': typeof LayoutAdminContentNewRoute
  '/admin/content/': typeof LayoutAdminContentIndexRoute
  '/admin/content/$animeId/': typeof LayoutAdminContentAnimeIdIndexRoute
  '/admin/content/$animeId/seasons/$seasonId': typeof LayoutAdminContentAnimeIdSeasonsSeasonIdRoute
  '/admin/content/$animeId/seasons/new': typeof LayoutAdminContentAnimeIdSeasonsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/comments': typeof LayoutAdminCommentsRoute
  '/admin/people': typeof LayoutAdminPeopleRoute
  '/admin/content/new': typeof LayoutAdminContentNewRoute
  '/admin/content': typeof LayoutAdminContentIndexRoute
  '/admin/content/$animeId': typeof LayoutAdminContentAnimeIdIndexRoute
  '/admin/content/$animeId/seasons/$seasonId': typeof LayoutAdminContentAnimeIdSeasonsSeasonIdRoute
  '/admin/content/$animeId/seasons/new': typeof LayoutAdminContentAnimeIdSeasonsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/comments': typeof LayoutAdminCommentsRoute
  '/_layout/admin/people': typeof LayoutAdminPeopleRoute
  '/_layout/admin/content/new': typeof LayoutAdminContentNewRoute
  '/_layout/admin/content/': typeof LayoutAdminContentIndexRoute
  '/_layout/admin/content/$animeId/': typeof LayoutAdminContentAnimeIdIndexRoute
  '/_layout/admin/content/$animeId/seasons/$seasonId': typeof LayoutAdminContentAnimeIdSeasonsSeasonIdRoute
  '/_layout/admin/content/$animeId/seasons/new': typeof LayoutAdminContentAnimeIdSeasonsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/settings'
    | '/admin/comments'
    | '/admin/people'
    | '/admin/content/new'
    | '/admin/content/'
    | '/admin/content/$animeId/'
    | '/admin/content/$animeId/seasons/$seasonId'
    | '/admin/content/$animeId/seasons/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/settings'
    | '/'
    | '/admin/comments'
    | '/admin/people'
    | '/admin/content/new'
    | '/admin/content'
    | '/admin/content/$animeId'
    | '/admin/content/$animeId/seasons/$seasonId'
    | '/admin/content/$animeId/seasons/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/comments'
    | '/_layout/admin/people'
    | '/_layout/admin/content/new'
    | '/_layout/admin/content/'
    | '/_layout/admin/content/$animeId/'
    | '/_layout/admin/content/$animeId/seasons/$seasonId'
    | '/_layout/admin/content/$animeId/seasons/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/people': {
      id: '/_layout/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof LayoutAdminPeopleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/comments': {
      id: '/_layout/admin/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof LayoutAdminCommentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/content/': {
      id: '/_layout/admin/content/'
      path: '/admin/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof LayoutAdminContentIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/content/new': {
      id: '/_layout/admin/content/new'
      path: '/admin/content/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof LayoutAdminContentNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/content/$animeId/': {
      id: '/_layout/admin/content/$animeId/'
      path: '/admin/content/$animeId'
      fullPath: '/admin/content/$animeId/'
      preLoaderRoute: typeof LayoutAdminContentAnimeIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/content/$animeId/seasons/new': {
      id: '/_layout/admin/content/$animeId/seasons/new'
      path: '/admin/content/$animeId/seasons/new'
      fullPath: '/admin/content/$animeId/seasons/new'
      preLoaderRoute: typeof LayoutAdminContentAnimeIdSeasonsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/content/$animeId/seasons/$seasonId': {
      id: '/_layout/admin/content/$animeId/seasons/$seasonId'
      path: '/admin/content/$animeId/seasons/$seasonId'
      fullPath: '/admin/content/$animeId/seasons/$seasonId'
      preLoaderRoute: typeof LayoutAdminContentAnimeIdSeasonsSeasonIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminCommentsRoute: typeof LayoutAdminCommentsRoute
  LayoutAdminPeopleRoute: typeof LayoutAdminPeopleRoute
  LayoutAdminContentNewRoute: typeof LayoutAdminContentNewRoute
  LayoutAdminContentIndexRoute: typeof LayoutAdminContentIndexRoute
  LayoutAdminContentAnimeIdIndexRoute: typeof LayoutAdminContentAnimeIdIndexRoute
  LayoutAdminContentAnimeIdSeasonsSeasonIdRoute: typeof LayoutAdminContentAnimeIdSeasonsSeasonIdRoute
  LayoutAdminContentAnimeIdSeasonsNewRoute: typeof LayoutAdminContentAnimeIdSeasonsNewRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminCommentsRoute: LayoutAdminCommentsRoute,
  LayoutAdminPeopleRoute: LayoutAdminPeopleRoute,
  LayoutAdminContentNewRoute: LayoutAdminContentNewRoute,
  LayoutAdminContentIndexRoute: LayoutAdminContentIndexRoute,
  LayoutAdminContentAnimeIdIndexRoute: LayoutAdminContentAnimeIdIndexRoute,
  LayoutAdminContentAnimeIdSeasonsSeasonIdRoute:
    LayoutAdminContentAnimeIdSeasonsSeasonIdRoute,
  LayoutAdminContentAnimeIdSeasonsNewRoute:
    LayoutAdminContentAnimeIdSeasonsNewRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
